// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: ButtonIcon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-icon-global-container-active": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-icon-global-container-disabled": "light-dark(transparent, transparent)",
        "button-icon-global-container-hover": "light-dark(rgb(238 242 247), rgb(0 32 77))",
        "button-icon-global-container-idle": "light-dark(transparent, transparent)"
      },
      "borderColor": {
        "button-icon-secondary-container-border-color-active": "light-dark(transparent, transparent)",
        "button-icon-secondary-container-border-color-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-icon-secondary-container-border-color-hover": "light-dark(transparent, transparent)",
        "button-icon-secondary-container-border-color-idle": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "fill": {
        "button-icon-global-icon-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-icon-global-icon-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-icon-global-icon-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-icon-global-icon-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "button-icon-global-container-height": "32px",
        "button-icon-global-container-padding-x": "8px",
        "button-icon-global-icon-size": "24px",
        "button-icon-secondary-container-border-width": "1px"
      },
      "borderRadius": {
        "button-icon-global-container-border-radius": "4px"
      }
    },
  },
};
