// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: form
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "form-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "form-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "form-disabled": "light-dark(rgb(248 250 252), rgb(0 21 51))",
        "form-circle-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "form-circle-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "textColor": {
        "form-description": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "form-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "form-error": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "form-text": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "form-placeholder": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "form-text-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "form-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "form-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "form-error": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "form-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "form-idle": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "fill": {
        "form-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "form-error": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "form-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "form-units-border-lg": "2px",
        "form-units-border-sm": "1px",
        "form-units-gap-lg": "8px",
        "form-units-gap-md": "4px",
        "form-units-gap-sm": "2px",
        "form-units-height-lg": "48px",
        "form-units-height-sm": "32px",
        "form-units-padding-x-lg": "16px",
        "form-units-padding-x-sm": "12px",
        "form-units-size-md": "16px",
        "form-units-size-sm": "8px",
        "form-units-width-max": "512px",
        "form-units-width-min": "256px"
      },
      "borderRadius": {
        "form-units-radius-lg": "24px",
        "form-units-radius-md": "4px",
        "form-units-radius-sm": "2px",
        "form-units-radius-xlg": "999px"
      }
    },
  },
};
