export {
  SidebarSecondary,
  SidebarSecondaryHeader,
  SidebarSecondaryContent,
  SidebarSecondaryFooter,
  SidebarSecondarySection,
  SidebarSecondarySectionLabel,
  SidebarSecondaryMenu,
  SidebarSecondaryMenuItem,
  SidebarSecondaryMenuItemExtras,
  SidebarSecondaryCollapseTrigger,
  sidebarSecondaryMenuItemVariants,
  type SidebarSecondaryProps,
  type SidebarSecondaryHeaderProps,
  type SidebarSecondaryMenuItemProps,
  type SidebarSecondaryMenuItemExtrasProps,
  type SidebarSecondaryCollapseTriggerProps,
} from './sidebar-secondary';
