// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: tree
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "tree-item-hover": "light-dark(rgb(226 245 244), rgb(3 58 54))",
        "tree-item-active": "light-dark(rgb(209 240 237), rgb(4 73 67))"
      },
      "textColor": {
        "tree-item": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "tree-title": "light-dark(rgb(255 255 255), rgb(255 255 255))"
      },
      "borderColor": {
        "tree-global": "light-dark(rgb(209 240 237), rgb(4 73 67))"
      },
      "fill": {
        "tree-item": "light-dark(rgb(51 153 145), rgb(51 153 145))"
      },
      "spacing": {
        "tree-global-padding-x": "16px",
        "tree-global-padding-y": "8px",
        "tree-global-width-min": "224px",
        "tree-item-gap": "8px",
        "tree-item-padding-y": "8px",
        "tree-nesting-padding-l1": "8px",
        "tree-nesting-padding-l2": "32px",
        "tree-nesting-padding-l3": "56px",
        "tree-nesting-padding-l4": "80px",
        "tree-nesting-padding-l5": "104px"
      }
    },
  },
};
