import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

import {
  DEFAULT_BRAND,
  listBrands,
  resolveFlat,
  resolveTree,
  type Scheme,
  type SdToken,
  type SdTree,
} from './resolve.ts';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolvePath(here, '..', 'dist');
const PREFIX = 'av';
const BANNER_CSS =
  '/* Generated by @acronis-platform/design-theme from @acronis-platform/design-tokens. Do not edit directly. */\n';
const BANNER_JS =
  '// Generated by @acronis-platform/design-theme from @acronis-platform/design-tokens. Do not edit directly.\n';

async function format(sd: StyleDictionary, platform: string): Promise<string> {
  await sd.hasInitialized;
  const [file] = await sd.formatPlatform(platform);
  return file.output as string;
}

function cssDictionary(scheme: Scheme, brand: string): StyleDictionary {
  return new StyleDictionary({
    log: { verbosity: 'silent' },
    tokens: resolveTree(scheme, brand),
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: PREFIX,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables',
            options: { selector: ':root', outputReferences: false },
          },
        ],
      },
    },
  });
}

/** Resolve a (scheme, brand) to a `--av-name` → value map via Style Dictionary. */
async function varMap(
  scheme: Scheme,
  brand: string
): Promise<Map<string, string>> {
  const css = await format(cssDictionary(scheme, brand), 'css');
  const map = new Map<string, string>();
  for (const match of css.matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    map.set(match[1], match[2].trim());
  }
  return map;
}

function cssBlock(selector: string, entries: [string, string][]): string {
  return `${selector} {\n${entries.map(([n, v]) => `  ${n}: ${v};`).join('\n')}\n}`;
}

async function buildCss(): Promise<void> {
  const brands = listBrands();
  const defaultLight = await varMap('light', DEFAULT_BRAND);
  const defaultDark = await varMap('dark', DEFAULT_BRAND);

  // Default brand at :root / .dark; other brands as class-scoped overrides
  // (`.brand`, `.brand.dark`) carrying only the tokens that differ.
  const parts = [
    cssBlock(':root', [...defaultLight]),
    cssBlock('.dark', [...defaultDark]),
  ];

  for (const brand of brands) {
    if (brand === DEFAULT_BRAND) continue;
    const light = await varMap('light', brand);
    const dark = await varMap('dark', brand);
    const lightDiff = [...light].filter(([n, v]) => defaultLight.get(n) !== v);
    const darkDiff = [...dark].filter(([n, v]) => defaultDark.get(n) !== v);
    parts.push(
      lightDiff.length
        ? cssBlock(`.${brand}`, lightDiff)
        : `/* brand "${brand}": no light overrides vs ${DEFAULT_BRAND} */`
    );
    parts.push(
      darkDiff.length
        ? cssBlock(`.${brand}.dark`, darkDiff)
        : `/* brand "${brand}": no dark overrides vs ${DEFAULT_BRAND} */`
    );
  }

  await mkdir(resolvePath(dist, 'css'), { recursive: true });
  await writeFile(
    resolvePath(dist, 'css/variables.css'),
    `${BANNER_CSS}\n${parts.join('\n\n')}\n`
  );
}

async function buildScss(): Promise<void> {
  const sd = new StyleDictionary({
    log: { verbosity: 'silent' },
    tokens: resolveTree('light', DEFAULT_BRAND),
    platforms: {
      scss: {
        transformGroup: 'scss',
        prefix: PREFIX,
        files: [
          {
            destination: '_variables.scss',
            format: 'scss/variables',
            options: { outputReferences: false },
          },
        ],
      },
    },
  });
  await mkdir(resolvePath(dist, 'scss'), { recursive: true });
  await writeFile(
    resolvePath(dist, 'scss/_variables.scss'),
    await format(sd, 'scss')
  );
}

interface TokenEntry {
  name: string;
  label: string;
}
interface TokenGroup {
  label: string;
  tokens: TokenEntry[];
}

/**
 * A display label for a token and the group it belongs to, derived from its
 * real path (the flat `--av-` name is lossy — `status-inverted` / `on-surface`
 * are indistinguishable from path separators once joined).
 */
function classify(path: string[]): { group: string; label: string } {
  if (path[0] === 'palette') {
    const family = path[1] ?? 'base';
    return {
      group: `palette · ${family}`,
      label: path.slice(2).join('-') || family,
    };
  }
  const channel = path[1] ?? '';
  const category = path[2] ?? '';
  return {
    group: `${channel} · ${category}`,
    label: path.slice(3).join('-') || category,
  };
}

/** Group the emitted color tokens by category (semantic first, palette ramps last). */
function collectGroups(): TokenGroup[] {
  const order: string[] = [];
  const byGroup = new Map<string, TokenEntry[]>();
  const walk = (node: SdTree, path: string[]): void => {
    for (const [key, child] of Object.entries(node)) {
      const next = [...path, key];
      if (typeof (child as SdToken).value === 'string') {
        const { group, label } = classify(next);
        if (!byGroup.has(group)) {
          byGroup.set(group, []);
          order.push(group);
        }
        byGroup.get(group)!.push({ name: next.join('-'), label });
      } else {
        walk(child as SdTree, next);
      }
    }
  };
  walk(resolveTree('light', DEFAULT_BRAND), []);

  const isPalette = (g: string) => g.startsWith('palette ·');
  const ordered = [
    ...order.filter((g) => !isPalette(g)),
    ...order.filter(isPalette),
  ];
  return ordered.map((label) => ({ label, tokens: byGroup.get(label)! }));
}

async function buildJs(): Promise<void> {
  const brands = listBrands();
  const byBrand: Record<
    string,
    { light: Record<string, string>; dark: Record<string, string> }
  > = {};
  for (const brand of brands) {
    byBrand[brand] = {
      light: resolveFlat('light', brand),
      dark: resolveFlat('dark', brand),
    };
  }

  const dir = resolvePath(dist, 'js');
  await mkdir(dir, { recursive: true });

  const groups = collectGroups();
  const js =
    `${BANNER_JS}` +
    `export const brands = ${JSON.stringify(brands)};\n\n` +
    `export const defaultBrand = ${JSON.stringify(DEFAULT_BRAND)};\n\n` +
    `export const tokens = ${JSON.stringify(byBrand, null, 2)};\n\n` +
    `export const light = tokens[defaultBrand].light;\n` +
    `export const dark = tokens[defaultBrand].dark;\n\n` +
    `export const groups = ${JSON.stringify(groups, null, 2)};\n`;
  await writeFile(resolvePath(dir, 'index.js'), js);

  const tokenUnion = Object.keys(byBrand[DEFAULT_BRAND].light)
    .map((k) => `  | '${k}'`)
    .join('\n');
  const brandUnion = brands.map((b) => `'${b}'`).join(' | ');
  const dts =
    `${BANNER_JS}` +
    `export type Brand = ${brandUnion};\n` +
    `export type Scheme = 'light' | 'dark';\n` +
    `export type TokenName =\n${tokenUnion};\n\n` +
    `export declare const brands: Brand[];\n` +
    `export declare const defaultBrand: Brand;\n` +
    `export declare const tokens: Record<Brand, Record<Scheme, Record<TokenName, string>>>;\n` +
    `export declare const light: Record<TokenName, string>;\n` +
    `export declare const dark: Record<TokenName, string>;\n` +
    `export interface TokenGroup { label: string; tokens: { name: TokenName; label: string }[] }\n` +
    `export declare const groups: TokenGroup[];\n`;
  await writeFile(resolvePath(dir, 'index.d.ts'), dts);
}

async function main(): Promise<void> {
  await Promise.all([buildCss(), buildScss(), buildJs()]);

  const brands = listBrands();
  const count = Object.keys(resolveFlat('light', DEFAULT_BRAND)).length;
  console.log(
    `✓ @acronis-platform/design-theme: built ${count} color tokens × ${brands.length} brand(s) [${brands.join(', ')}] → css, scss, js`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
