// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: ButtonGroup
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-group-global-box-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "button-group-global-box-hover": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "button-group-global-box-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "button-group-global-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "button-group-global-container-border-color": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "button-group-global-separator": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fontFamily": {
        "button-group-global-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "button-group-global-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "button-group-global-box-height": "32px",
        "button-group-global-box-padding-x": "12px",
        "button-group-global-box-padding-y": "8px",
        "button-group-global-container-border-width": "1px",
        "button-group-global-separator-border-width": "1px"
      },
      "borderRadius": {
        "button-group-global-container-border-radius": "4px"
      }
    },
  },
};
