// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: Button
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-destructive-container-active": "light-dark(rgb(173 31 31), rgb(248 195 195))",
        "button-destructive-container-disabled": "light-dark(rgb(253 237 237), rgb(87 15 15))",
        "button-destructive-container-hover": "light-dark(rgb(195 34 34), rgb(244 154 154))",
        "button-destructive-container-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "button-primary-container-active": "light-dark(rgb(48 50 54), rgb(18 77 161))",
        "button-primary-container-disabled": "light-dark(rgb(215 217 219), rgb(48 50 54))",
        "button-primary-container-hover": "light-dark(rgb(61 63 67), rgb(23 99 207))",
        "button-primary-container-idle": "light-dark(rgb(73 76 80), rgb(81 157 246))",
        "button-secondary-container-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "button-secondary-container-disabled": "light-dark(transparent, transparent)",
        "button-secondary-container-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "button-secondary-container-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "button-ai-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-label-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.302))",
        "button-ai-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.302))",
        "button-destructive-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ghost-label-active": "light-dark(rgb(48 50 54), rgb(228 229 231))",
        "button-ghost-label-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "button-ghost-label-hover": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "button-ghost-label-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-primary-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-label-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.302))",
        "button-primary-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-secondary-label-active": "light-dark(rgb(48 50 54), rgb(228 229 231))",
        "button-secondary-label-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "button-secondary-label-hover": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "button-secondary-label-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "borderColor": {
        "button-secondary-container-border-color-active": "light-dark(transparent, transparent)",
        "button-secondary-container-border-color-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "button-secondary-container-border-color-hover": "light-dark(transparent, transparent)",
        "button-secondary-container-border-color-idle": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fill": {
        "button-ai-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-icon-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ghost-icon-active": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-ghost-icon-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "button-ghost-icon-hover": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-ghost-icon-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-primary-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-icon-disabled": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "button-primary-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-secondary-icon-active": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-secondary-icon-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "button-secondary-icon-hover": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-secondary-icon-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "fontFamily": {
        "button-global-label-text-style": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-active": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-disabled": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-hover": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-idle": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "button-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-active": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-disabled": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-hover": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-idle": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "button-global-container-gap": "8px",
        "button-global-container-height": "32px",
        "button-global-container-padding-y": "8px",
        "button-global-icon-size": "16px",
        "button-ai-container-padding-x": "12px",
        "button-ai-container-width-min": "64px",
        "button-destructive-container-padding-x": "12px",
        "button-destructive-container-width-min": "64px",
        "button-ghost-container-padding-x": "0px",
        "button-primary-container-padding-x": "12px",
        "button-primary-container-width-min": "64px",
        "button-secondary-container-border-width": "1px",
        "button-secondary-container-padding-x": "12px",
        "button-secondary-container-width-min": "64px"
      },
      "borderRadius": {
        "button-global-container-border-radius": "4px"
      }
    },
  },
};
