// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: Checkbox
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "checkbox-checked-box-active": "light-dark(rgb(48 50 54), rgb(18 77 161))",
        "checkbox-checked-box-disabled": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "checkbox-checked-box-hover": "light-dark(rgb(61 63 67), rgb(23 99 207))",
        "checkbox-checked-box-idle": "light-dark(rgb(73 76 80), rgb(81 157 246))",
        "checkbox-indeterminate-box-active": "light-dark(rgb(48 50 54), rgb(18 77 161))",
        "checkbox-indeterminate-box-disabled": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "checkbox-indeterminate-box-hover": "light-dark(rgb(61 63 67), rgb(23 99 207))",
        "checkbox-indeterminate-box-idle": "light-dark(rgb(73 76 80), rgb(81 157 246))",
        "checkbox-unchecked-box-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "checkbox-unchecked-box-disabled": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "checkbox-unchecked-box-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "checkbox-unchecked-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "checkbox-global-description": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-global-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "checkbox-checked-box-border-color-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-checked-box-border-color-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "checkbox-checked-box-border-color-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-checked-box-border-color-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-indeterminate-box-border-color-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-indeterminate-box-border-color-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "checkbox-indeterminate-box-border-color-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-indeterminate-box-border-color-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-unchecked-box-border-color-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-unchecked-box-border-color-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "checkbox-unchecked-box-border-color-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "checkbox-unchecked-box-border-color-idle": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fill": {
        "checkbox-checked-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "checkbox-checked-icon-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "checkbox-checked-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "checkbox-checked-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "checkbox-indeterminate-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "checkbox-indeterminate-icon-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "checkbox-indeterminate-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "checkbox-indeterminate-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))"
      },
      "fontFamily": {
        "checkbox-global-description-text-style": "Inter, system-ui, sans-serif",
        "checkbox-global-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "checkbox-global-description-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "checkbox-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "checkbox-global-box-border-width": "1px",
        "checkbox-global-box-margin-y": "4px",
        "checkbox-global-box-size": "16px",
        "checkbox-global-container-gap": "8px",
        "checkbox-global-container-width-max": "632px",
        "checkbox-global-container-width-min": "16px",
        "checkbox-global-container-content-gap": "0px",
        "checkbox-global-container-content-width-max": "632px"
      },
      "borderRadius": {
        "checkbox-global-box-border-radius": "2px"
      }
    },
  },
};
