// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: InputOTP
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-o-t-p-box": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-o-t-p-box-border-error": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-o-t-p-placeholder": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-o-t-p-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "input-o-t-p-box-border-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-o-t-p-box-border-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-o-t-p-box-border-idle": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fontFamily": {
        "input-otp-placeholder-text-style": "Inter, system-ui, sans-serif",
        "input-otp-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-otp-placeholder-text-style": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-otp-value-text-style": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-otp-box-border-width": "1px",
        "input-otp-box-height": "76px",
        "input-otp-box-padding-x": "12px",
        "input-otp-box-padding-y": "12px",
        "input-otp-box-width": "48px"
      },
      "borderRadius": {
        "input-otp-box-border-radius": "4px"
      }
    },
  },
};
