// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: Link
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "fill": {
        "link-external-icon-active": "light-dark(rgb(48 50 54), rgb(228 229 231))",
        "link-external-icon-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "link-external-icon-hover": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "link-external-icon-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "fontFamily": {
        "link-text-style-active": "Inter, system-ui, sans-serif",
        "link-text-style-disabled": "Inter, system-ui, sans-serif",
        "link-text-style-hover": "Inter, system-ui, sans-serif",
        "link-text-style-idle": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "link-text-style-active": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-disabled": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-hover": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-idle": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "link-container-gap": "4px",
        "link-container-height": "32px"
      }
    },
  },
};
