// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: Loading
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "loading-element-container-primary": "light-dark(rgb(255 255 255 / 0.949), rgb(48 50 54 / 0.949))",
        "loading-element-container-secondary": "light-dark(rgb(248 250 252 / 0.949), rgb(24 25 27 / 0.949))",
        "loading-screen-container": "light-dark(rgb(25 27 35 / 0.898), rgb(25 27 35 / 0.898))"
      },
      "textColor": {
        "loading-element-label": "light-dark(rgb(25 27 35), rgb(255 255 255))",
        "loading-inline-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "loading-screen-label": "light-dark(rgb(255 255 255), rgb(255 255 255))"
      },
      "fill": {
        "loading-element-icon": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "loading-inline-icon": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "loading-screen-icon": "light-dark(rgb(255 255 255), rgb(255 255 255))"
      },
      "fontFamily": {
        "loading-element-label-text-style": "Inter, system-ui, sans-serif",
        "loading-inline-label-text-style": "Inter, system-ui, sans-serif",
        "loading-screen-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "loading-element-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "loading-inline-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "loading-screen-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "loading-element-container-gap": "8px",
        "loading-element-container-padding-x": "16px",
        "loading-element-container-padding-y": "16px",
        "loading-element-icon-size": "32px",
        "loading-inline-container-gap": "8px",
        "loading-inline-container-height": "24px",
        "loading-inline-icon-size": "16px",
        "loading-screen-container-gap": "8px",
        "loading-screen-container-padding-x": "16px",
        "loading-screen-container-padding-y": "16px",
        "loading-screen-icon-size": "48px"
      }
    },
  },
};
