// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: Table
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "table-header-cell-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "table-header-cell-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "table-header-cell-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "table-data-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "table-data-value-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "table-header-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "table-global-row-border-color": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fill": {
        "table-header-sort-icon-active": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "table-header-sort-icon-inactive": "light-dark(rgb(201 204 207), rgb(73 76 80))"
      },
      "fontFamily": {
        "table-data-value-text-style": "Inter, system-ui, sans-serif",
        "table-header-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "table-data-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "table-header-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "table-data-gap": "8px",
        "table-header-gap": "8px",
        "table-header-sort-icon-size": "16px",
        "table-global-cell-icon-margin-y": "4px",
        "table-global-cell-min-height": "40px",
        "table-global-cell-padding-x": "16px",
        "table-global-cell-padding-y": "8px",
        "table-global-cell-tag-margin-y": "2px",
        "table-global-row-border-width": "1px"
      }
    },
  },
};
