// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: ButtonIconInput
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-icon-input-error-container-active": "light-dark(rgb(251 218 218), rgb(130 23 23))",
        "button-icon-input-error-container-disabled": "light-dark(transparent, transparent)",
        "button-icon-input-error-container-hover": "light-dark(rgb(253 237 237), rgb(87 15 15))",
        "button-icon-input-error-container-idle": "light-dark(transparent, transparent)",
        "button-icon-input-normal-container-active": "light-dark(rgb(226 235 245), rgb(48 50 54))",
        "button-icon-input-normal-container-disabled": "light-dark(transparent, transparent)",
        "button-icon-input-normal-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "button-icon-input-normal-container-idle": "light-dark(transparent, transparent)"
      },
      "fill": {
        "button-icon-input-error-icon-active": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "button-icon-input-error-icon-hover": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "button-icon-input-error-icon-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "button-icon-input-normal-icon-active": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "button-icon-input-normal-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-icon-input-normal-icon-hover": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "button-icon-input-normal-icon-idle": "light-dark(rgb(23 99 207), rgb(81 157 246))"
      },
      "spacing": {
        "button-icon-input-global-container-height": "20px",
        "button-icon-input-global-container-padding-x": "2px",
        "button-icon-input-global-container-padding-y": "2px",
        "button-icon-input-global-container-width": "20px",
        "button-icon-input-error-icon-size": "16px",
        "button-icon-input-normal-icon-size": "16px"
      },
      "borderRadius": {
        "button-icon-input-global-container-border-radius": "4px"
      }
    },
  },
};
