// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: Chat
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "chat-container": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "chat-menu-item-hint": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "chat-menu-item-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "chat-global-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "chat-menu-item-icon": "light-dark(rgb(23 99 207), rgb(81 157 246))"
      },
      "fontFamily": {
        "chat-menu-item-hint-text-style": "Inter, system-ui, sans-serif",
        "chat-menu-item-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "chat-menu-item-hint-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "chat-menu-item-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "chat-global-border-width": "1px",
        "chat-container-collapsed-width": "48px",
        "chat-container-expanded-max-width": "512px",
        "chat-container-expanded-min-width": "320px",
        "chat-header-height": "64px",
        "chat-header-padding-x": "16px",
        "chat-menu-item-collapsed-max-width": "48px",
        "chat-menu-item-expanded-gap": "8px",
        "chat-menu-item-expanded-min-width": "224px",
        "chat-menu-item-height": "40px",
        "chat-menu-item-padding-x": "16px",
        "chat-sidebar-width": "256px"
      }
    },
  },
};
