// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: Footer
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "borderColor": {
        "footer-default-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "spacing": {
        "footer-global-gap": "16px",
        "footer-global-height": "64px",
        "footer-global-padding-x": "16px",
        "footer-default-border-width": "1px"
      }
    },
  },
};
