// The tailwind build domain (`<filter>-tailwind`): turn the resolved tokens into
// a per-brand Tailwind preset (`tokens-pd/tailwind.preset.<brand>.js`) consumed
// via `@config`. Values are BAKED (resolved literals — colors as `light-dark()`,
// dimensions as `px`, gradients as `linear-gradient()`), so the preset has no
// dependency on the `--ui-*` custom properties; light/dark still switches at
// runtime through `light-dark()`. Reuses the css stage's SD resolve (`./tokens`).

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';

import type { TransformedToken } from 'style-dictionary/types';

import { type Filter, rel, tailwindDir, tailwindPreset } from './platforms';
import { BRANDS, resolveColorMap, resolveTokens } from './tokens';

// Tailwind theme namespaces we populate from tokens. Keys keep the `ui-` prefix
// (so utilities read `bg-ui-…`, `text-ui-…`, `rounded-ui-…`).
interface ThemeExtend {
  colors: Record<string, string>;
  backgroundImage: Record<string, string>;
  fontFamily: Record<string, string>;
  fontSize: Record<string, [string, Record<string, string>]>;
  spacing: Record<string, string>;
  borderRadius: Record<string, string>;
}

const emptyTheme = (): ThemeExtend => ({
  colors: {},
  backgroundImage: {},
  fontFamily: {},
  fontSize: {},
  spacing: {},
  borderRadius: {},
});

/** Parse a `prop: value;`-per-line declaration block into a property map. */
function parseDeclarations(block: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of block.split('\n')) {
    const match = /^\s*([\w-]+)\s*:\s*(.+?);?\s*$/.exec(line);
    if (match) out[match[1]] = match[2];
  }
  return out;
}

/** Add a resolved typography composite to the fontSize / fontFamily namespaces. */
function addTypography(theme: ThemeExtend, key: string, block: string): void {
  const decls = parseDeclarations(block);
  const size = decls['font-size'];
  if (size) {
    const extra: Record<string, string> = {};
    if (decls['line-height']) extra.lineHeight = decls['line-height'];
    if (decls['letter-spacing']) extra.letterSpacing = decls['letter-spacing'];
    if (decls['font-weight']) extra.fontWeight = decls['font-weight'];
    theme.fontSize[key] = [size, extra];
  }
  if (decls['font-family']) theme.fontFamily[key] = decls['font-family'];
}

/** Build one brand's `theme.extend` from its resolved tokens (baked values). */
function buildThemeExtend(
  tokens: TransformedToken[],
  darkColors: Map<string, string>
): ThemeExtend {
  const theme = emptyTheme();
  for (const token of tokens) {
    const key = token.name; // already `ui-…`
    const value = typeof token.$value === 'string' ? token.$value : null;
    if (token.$type === 'color') {
      if (value === null) continue;
      const dark = darkColors.get(token.path.join('.')) ?? value;
      theme.colors[key] = `light-dark(${value}, ${dark})`;
    } else if (token.$type === 'gradient') {
      if (value !== null) theme.backgroundImage[key] = value;
    } else if (token.$type === 'typography') {
      if (value !== null) addTypography(theme, key, value);
    } else if (token.$type === 'dimension') {
      if (value === null) continue;
      if (key.includes('radius')) theme.borderRadius[key] = value;
      else theme.spacing[key] = value;
    }
  }
  return theme;
}

/** Drop empty namespaces so the emitted preset stays tidy. */
function prune(theme: ThemeExtend): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(theme).filter(([, v]) => Object.keys(v as object).length > 0)
  );
}

function renderPreset(brand: string, theme: ThemeExtend): string {
  const extend = JSON.stringify(prune(theme), null, 2);
  return (
    `// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.\n` +
    `// Source: @acronis-platform/design-tokens • brand: ${brand}\n` +
    `// Tailwind preset (baked token values) — consume via \`@config\`.\n\n` +
    `export default {\n  theme: {\n    extend: ${extend.replace(/\n/g, '\n    ')},\n  },\n};\n`
  );
}

const DTS =
  `// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.\n` +
  `declare const preset: { theme: { extend: Record<string, unknown> } };\n` +
  `export default preset;\n`;

export async function buildTailwind(filter: Filter): Promise<void> {
  rmSync(tailwindDir(), { recursive: true, force: true });
  mkdirSync(tailwindDir(), { recursive: true });
  for (const brand of BRANDS) {
    const darkColors = await resolveColorMap(filter, brand, 'dark');
    const tokens = await resolveTokens(filter, brand, 'light');
    const theme = buildThemeExtend(tokens, darkColors);

    const dest = tailwindPreset(brand.name);
    writeFileSync(dest, renderPreset(brand.name, theme));
    writeFileSync(dest.replace(/\.js$/, '.d.ts'), DTS);
    console.log(`✓ ${rel(dest)}`);
  }
}
