import { createRequire } from 'node:module';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { toComponentName } from '../src/lib/naming.ts';
import { PACKS, type PackConfig } from './packs.ts';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const srcPacks = resolve(here, '..', 'src', 'packs');

// design-assets ships JSON manifests + SVG sources; resolve its root from the
// package.json export and read packs/rules off the filesystem.
const assetsRoot = dirname(
  require.resolve('@acronis-platform/design-assets/package.json')
);

interface Rule {
  kind: 'scale' | 'stroke';
  target: { value: number; unit: string };
}
interface Manifest {
  name: string;
  values: Record<string, { default?: boolean; $rules?: string[] }>;
  assets: Record<string, { values: Record<string, { $file?: string }> }>;
}

function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

async function loadRules(): Promise<Map<string, Rule>> {
  const names = [
    'scale-16',
    'scale-32',
    'scale-96',
    'stroke-1-6',
    'stroke-2-5',
  ];
  const rules = new Map<string, Rule>();
  for (const name of names) {
    const file = resolve(assetsRoot, 'rules', `${name}.json`);
    rules.set(name, JSON.parse(await readFile(file, 'utf8')) as Rule);
  }
  return rules;
}

/** kebab-attr="…" → camelAttr="…" for JSX (leaving aria- and data- attrs alone). */
function camelCaseAttrs(s: string): string {
  return s.replace(/\s([a-zA-Z][\w]*(?:-[\w]+)+)=/g, (match, name: string) => {
    if (/^(aria|data)-/.test(name)) return match;
    return (
      ' ' + name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) + '='
    );
  });
}

/** Prefix gradient/clip ids (and their url(#…) refs) to avoid cross-icon collisions. */
function namespaceIds(s: string, slug: string): string {
  return s
    .replace(/\bid="([^"]+)"/g, (_, id: string) => `id="${slug}-${id}"`)
    .replace(/url\(#([^)]+)\)/g, (_, id: string) => `url(#${slug}-${id})`);
}

/** Strip a 24px master SVG down to JSX-ready inner markup per the pack config. */
function toInnerJsx(svg: string, pack: PackConfig, slug: string): string {
  let out = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i)?.[1] ?? '';
  if (!pack.multicolor) {
    // mono → drop authored colors so the <svg>'s currentColor takes over.
    out = out.replace(/\sstroke="[^"]*"/g, '').replace(/\sfill="[^"]*"/g, '');
  } else {
    // multicolor → keep colors, but namespace ids so gradients don't clash.
    out = namespaceIds(out, slug);
  }
  if (pack.paint === 'stroke') {
    // stroke width + line caps come from the <svg> (rule-driven / round).
    out = out
      .replace(/\sstroke-width="[^"]*"/g, '')
      .replace(/\sstroke-linecap="[^"]*"/g, '')
      .replace(/\sstroke-linejoin="[^"]*"/g, '');
  }
  out = camelCaseAttrs(out);
  return out
    .split(/(?<=\/>|>)\s*(?=<)/)
    .map((line) => line.trim())
    .filter(Boolean)
    .join('\n      ');
}

function wrapperSource(
  pack: PackConfig,
  strokeMap: Record<number, number>
): string {
  const head =
    `// Generated by scripts/generate-icons.ts. Do not edit.\n` +
    `import { SvgIcon, type IconProps, type SvgIconProps } from '../../lib/svg-icon';\n\n` +
    `export type { IconProps };\n\n`;
  const props = `props: Omit<SvgIconProps, 'strokeWidthBySize'>`;
  if (pack.paint === 'stroke') {
    // mono forces currentColor; multicolor keeps each path's authored stroke.
    const stroke = pack.multicolor ? '' : ' stroke="currentColor"';
    return (
      head +
      `const STROKE_WIDTH_BY_SIZE: Record<number, number> = ${JSON.stringify(strokeMap)};\n\n` +
      `export function PackIcon(${props}) {\n` +
      `  return (\n` +
      `    <SvgIcon\n` +
      `      fill="none"${stroke}\n` +
      `      strokeLinecap="round"\n` +
      `      strokeLinejoin="round"\n` +
      `      strokeWidthBySize={STROKE_WIDTH_BY_SIZE}\n` +
      `      {...props}\n` +
      `    />\n  );\n}\n`
    );
  }
  // solid
  const fill = pack.multicolor ? '' : ' fill="currentColor"';
  return (
    head +
    `export function PackIcon(${props}) {\n` +
    `  return <SvgIcon${fill} {...props} />;\n}\n`
  );
}

async function generatePack(
  pack: PackConfig,
  rules: Map<string, Rule>
): Promise<number> {
  const manifest = JSON.parse(
    await readFile(
      resolve(assetsRoot, 'packs', `${pack.assetPack}.json`),
      'utf8'
    )
  ) as Manifest;

  const defaultSize = Object.entries(manifest.values).find(
    ([, v]) => v.default
  )?.[0];
  if (!defaultSize)
    throw new Error(`${pack.assetPack}: no default size in manifest`);

  const outDir = resolve(srcPacks, pack.name);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(resolve(outDir, 'icons'), { recursive: true });

  const assetNames = Object.keys(manifest.assets).sort();
  let viewBox = '0 0 24 24';
  let masterStroke = 2;

  const components: { name: string; component: string; file: string }[] = [];
  for (const assetName of assetNames) {
    const file = manifest.assets[assetName].values[defaultSize]?.$file;
    if (!file) continue;
    const svg = await readFile(resolve(assetsRoot, file), 'utf8');
    viewBox = svg.match(/viewBox="([^"]*)"/)?.[1] ?? viewBox;
    masterStroke = Number(
      svg.match(/stroke-width="([\d.]+)"/)?.[1] ?? masterStroke
    );

    const component = toComponentName(assetName);
    const inner = toInnerJsx(svg, pack, assetName);
    const body =
      `import { PackIcon, type IconProps } from '../icon';\n\n` +
      `export function ${component}(props: IconProps) {\n` +
      `  return (\n    <PackIcon viewBox="${viewBox}" {...props}>\n      ${inner}\n    </PackIcon>\n  );\n}\n`;
    await writeFile(resolve(outDir, 'icons', `${assetName}.tsx`), body);
    components.push({
      name: assetName,
      component,
      file: `./icons/${assetName}`,
    });
  }

  // Stroke-width map (stroke packs only): rendered px → viewBox user units.
  const viewBoxSize = Number(viewBox.split(/\s+/)[2]) || 24;
  const strokeMap: Record<number, number> = {};
  if (pack.paint === 'stroke') {
    for (const [sizeKey, value] of Object.entries(manifest.values)) {
      const renderSize = Number(sizeKey);
      const strokeRuleName = value.$rules?.find(
        (r) => rules.get(r)?.kind === 'stroke'
      );
      const strokePx = strokeRuleName
        ? rules.get(strokeRuleName)!.target.value
        : masterStroke;
      strokeMap[renderSize] = round((strokePx * viewBoxSize) / renderSize);
    }
  }

  await writeFile(resolve(outDir, 'icon.tsx'), wrapperSource(pack, strokeMap));

  const imports = components
    .map((c) => `import { ${c.component} } from '${c.file}';`)
    .join('\n');
  const exportList = `export {\n${components.map((c) => `  ${c.component},`).join('\n')}\n};`;
  const registry =
    `export const icons = {\n` +
    components.map((c) => `  '${c.name}': ${c.component},`).join('\n') +
    `\n} as const;`;
  const index =
    `// Generated by scripts/generate-icons.ts from @acronis-platform/design-assets. Do not edit.\n` +
    `export type { IconProps } from './icon';\n\n` +
    `${imports}\n\n${exportList}\n\n${registry}\n\n` +
    `export type IconName = keyof typeof icons;\n`;
  await writeFile(resolve(outDir, 'index.ts'), index);

  return components.length;
}

async function main(): Promise<void> {
  const rules = await loadRules();
  await mkdir(srcPacks, { recursive: true });
  for (const pack of PACKS) {
    const count = await generatePack(pack, rules);
    console.log(`✓ icons-react: ${pack.name} — ${count} icons`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
