export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
  TableActions,
  TableSettings,
  type TableRowProps,
  type TableHeadProps,
  type TableCellProps,
  type TableActionsProps,
  type TableSettingsProps,
} from './table';
