import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

import {
  resolveFlat,
  resolveTree,
  type Brand,
  type Scheme,
} from './resolve.ts';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolvePath(here, '..', 'dist');

// First iteration ships the default Acronis brand with both color schemes.
// `brand-b` is one more entry away once it's needed.
const BRAND: Brand = 'acronis';
const PREFIX = 'av';

/** Style Dictionary stamps every file with a "Do not edit directly" block. */
function stripHeader(output: string): string {
  return output.replace(/^\s*\/\*\*[\s\S]*?\*\/\s*/, '').trim();
}

/**
 * Format (don't write) a platform in-memory, returning the single file's
 * output string. `formatPlatform` runs the transform + format pipeline
 * without touching disk, so we can compose the result ourselves.
 */
async function format(sd: StyleDictionary, platform: string): Promise<string> {
  await sd.hasInitialized;
  const [file] = await sd.formatPlatform(platform);
  return file.output as string;
}

function cssDictionary(scheme: Scheme, selector: string): StyleDictionary {
  return new StyleDictionary({
    log: { verbosity: 'silent' },
    tokens: resolveTree(scheme, BRAND),
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: PREFIX,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables',
            options: { selector, outputReferences: false },
          },
        ],
      },
    },
  });
}

async function buildCss(): Promise<void> {
  // One file with both selectors — `css/variables` only emits one selector
  // per call, so format light (`:root`) and dark (`.dark`) and join them.
  const light = stripHeader(
    await format(cssDictionary('light', ':root'), 'css')
  );
  const dark = stripHeader(await format(cssDictionary('dark', '.dark'), 'css'));
  const banner =
    '/* Generated by @acronis-platform/theme from @acronis-platform/tokens. Do not edit directly. */\n\n';
  await mkdir(resolvePath(dist, 'css'), { recursive: true });
  await writeFile(
    resolvePath(dist, 'css/variables.css'),
    `${banner}${light}\n\n${dark}\n`
  );
}

async function buildScss(): Promise<void> {
  const sd = new StyleDictionary({
    log: { verbosity: 'silent' },
    tokens: resolveTree('light', BRAND),
    platforms: {
      scss: {
        transformGroup: 'scss',
        prefix: PREFIX,
        files: [
          {
            destination: '_variables.scss',
            format: 'scss/variables',
            options: { outputReferences: false },
          },
        ],
      },
    },
  });
  await mkdir(resolvePath(dist, 'scss'), { recursive: true });
  await writeFile(
    resolvePath(dist, 'scss/_variables.scss'),
    await format(sd, 'scss')
  );
}

async function buildJs(): Promise<void> {
  const light = resolveFlat('light', BRAND);
  const dark = resolveFlat('dark', BRAND);
  const dir = resolvePath(dist, 'js');
  await mkdir(dir, { recursive: true });

  const banner =
    '// Generated by @acronis-platform/theme from @acronis-platform/tokens. Do not edit directly.\n';
  const js =
    `${banner}` +
    `export const light = ${JSON.stringify(light, null, 2)};\n\n` +
    `export const dark = ${JSON.stringify(dark, null, 2)};\n\n` +
    `export const tokens = { light, dark };\n`;
  await writeFile(resolvePath(dir, 'index.js'), js);

  const union = Object.keys(light)
    .map((k) => `  | '${k}'`)
    .join('\n');
  const dts =
    `${banner}` +
    `export type TokenName =\n${union};\n\n` +
    `export declare const light: Record<TokenName, string>;\n` +
    `export declare const dark: Record<TokenName, string>;\n` +
    `export declare const tokens: { light: Record<TokenName, string>; dark: Record<TokenName, string> };\n` +
    `export type Scheme = keyof typeof tokens;\n`;
  await writeFile(resolvePath(dir, 'index.d.ts'), dts);
}

async function main(): Promise<void> {
  await Promise.all([buildCss(), buildScss(), buildJs()]);

  const count = Object.keys(resolveFlat('light', BRAND)).length;
   
  console.log(
    `✓ @acronis-platform/theme: built ${count} color tokens (brand="${BRAND}") → css, scss, js`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
