// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: Dialog
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "dialog-container": "light-dark(rgb(244 245 245), rgb(24 25 27))"
      },
      "borderColor": {
        "dialog-header-border-color": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fontFamily": {
        "dialog-header-title-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "dialog-header-title-text-style": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "dialog-body-gap": "12px",
        "dialog-body-height-min": "72px",
        "dialog-body-padding-y": "16px",
        "dialog-container-height-min": "224px",
        "dialog-container-size-md": "632px",
        "dialog-container-size-sm": "512px",
        "dialog-container-width-min": "256px",
        "dialog-header-border-width": "1px",
        "dialog-header-gap": "16px",
        "dialog-header-height": "64px",
        "dialog-header-padding-x": "16px"
      },
      "borderRadius": {
        "dialog-container-border-radius": "8px"
      }
    },
  },
};
