// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: Popover
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "popover-container": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "borderColor": {
        "popover-container-border-color": "light-dark(rgb(109 114 120), rgb(109 114 120))"
      },
      "spacing": {
        "popover-body-gap": "12px",
        "popover-body-padding-y": "16px",
        "popover-container-border-width": "1px",
        "popover-container-max-width": "512px",
        "popover-container-min-width": "320px"
      },
      "borderRadius": {
        "popover-container-border-radius": "4px"
      }
    },
  },
};
