name: UI - Release && Publish to NPM

on:
  release:
    types: [ published ]  # Triggers when you publish a release through GitHub UI
  workflow_dispatch:      # Enables manual trigger via GitHub web

permissions:
  contents: write
  packages: write  # For GitHub packages (optional)
  id-token: write  # Required for OIDC trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0  # match package.json
          run_install: false

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main  # Always checkout main branch, not the tag
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Publish NPM Package
        uses: phucbm/publish-npm-action@v1  # Docs https://github.com/phucbm/publish-npm-action
        with:
          skip-tests: ${{ github.event.inputs.skip-tests || 'false' }}
